### PR TITLE
Fixed the local to UTC date bug that won't increase the date and the hours once it reaches the end of the UTC date.

### PR DESCRIPTION
**Pull request by lsitu**
Hi Andrew,
The second bug should be fixed now, see commit https://github.com/awoods/modeshape/commit/f1c7c73f8c7771cfa5abbc39e740a414a9547fa0 . I am seeing it strange that with the LocalDateTime instance constructed from LocalDate.now(), the date and hours won't incremented when it reaches 24 (00) during converting to UTC time. I think that's why it always failed at night.

Longshou

### CODE REVIEW

**Comment by awoods** [comment]
This is great. The Modeshape team will likely want a test that your second commit fixes. Do you think you can create a simple unit test?

**Comment by lsitu** [comment]
Hi Andrew,
It seems to be a little tricky since the bug is bund to the system clock and triggered at a specific time period. But if we do a test at some time period (the equivalent UTC time change to a new date while local time hasn't changed), it'll failed without our changes. If this is not enough, is there a way to adjust the system clock for a 24 hours testing?

**Comment by lsitu** [comment]
Do you have any ideas for the unit test? It looks like the 24 hours timespan unit test you coded previously should be the way to go unless we add in other test frameworks. I tried to build the Fedora modeshape5 branch several times from time to time and I always got it successful now. Do you see any issues?

**Comment by lsitu** [comment]
@awoods With the bug can only be triggered in the period when a new UTC date starts while the local date hasn't  changed to a new local date, what else do you think we should do to fix this bug for Modeshape?

**Comment by awoods** [comment]
@lsitu, are you suggesting that your commit does not fix the issue?
https://github.com/awoods/modeshape/pull/2/commits/f1c7c73f8c7771cfa5abbc39e740a414a9547fa0

**Comment by lsitu** [comment]
@awoods My commits fixed the bugs! My question is that what's the way to prove that the bug is fixed as you suggested.  Maybe just suggest to test it during that time period when UTC time is changed to a new date while local date hasn't changed to a new local date?

**Comment by awoods** [comment]
I am verifying your fixes (tonight :wink:), then will submit the issue to ModeShape. If they as for more testing, we can act then.

**Comment by lsitu** [comment]
It sounds good. Thanks.

**Pull request closed without merging**
